settings:
  name: BlueXP tiering
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: BlueXP tiering docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about BlueXP tiering
          url: /concept-cloud-tiering.html
        - title: Tier on-prem data to the cloud
          entries:
            - title: Tier to Amazon S3
              url: /task-tiering-onprem-aws.html
            - title: Tier to Azure Blob storage
              url: /task-tiering-onprem-azure.html
            - title: Tier to Google Cloud Storage
              url: /task-tiering-onprem-gcp.html
            - title: Tier to StorageGRID
              url: /task-tiering-onprem-storagegrid.html
            - title: Tier to S3 object storage
              url: /task-tiering-onprem-s3-compat.html
        - title: Set up licensing
          url: /task-licensing-cloud-tiering.html
        - title: Monitor the status of tiering alerts
          url: /task-monitor-tiering-alerts.html
        - title: FAQ
          url: /faq-cloud-tiering.html
    - title: Use BlueXP tiering
      entries:
        - title: Manage data tiering
          url: /task-managing-tiering.html
        - title: Manage object storage
          url: /task-managing-object-storage.html
        - title: Test cloud performance
          url: /task-tiering-test.html
        - title: View tiering overview for all clusters
          url: /task-tiering-onprem-overview.html
    - title: Reference
      entries:
        - title: Supported Amazon S3 storage classes and regions
          url: /reference-aws-support.html
        - title: Supported Azure access tiers and regions
          url: /reference-azure-support.html
        - title: Supported Google Cloud storage classes and regions
          url: /reference-google-support.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about BlueXP tiering
          url: concept-cloud-tiering.html
        - title: What's New
          url: whats-new.html
        - title: Set up licensing
          url: task-licensing-cloud-tiering.html
    - title: Tier on-prem ONTAP data to the cloud
      links:
        - title: Tier to Amazon S3
          url: task-tiering-onprem-aws.html
        - title: Tier to Azure Blob
          url: task-tiering-onprem-azure.html
        - title: Tier to Google Cloud
          url: task-tiering-onprem-gcp.html
        - title: Tier to StorageGRID
          url: task-tiering-onprem-storagegrid.html
        - title: Tier to generic S3
          url: task-tiering-onprem-s3-compat.html
    - title: Manage tiering settings
      links:
        - title: Change a volume's tiering policy
          url: task-managing-tiering.html#changing-a-volumes-tiering-policy
        - title: Review tiering info for a cluster
          url: task-managing-tiering.html#reviewing-tiering-info-for-a-cluster
        - title: Tier data from additional volumes
          url: task-managing-tiering.html#tiering-data-from-additional-volumes
        - title: Change the bandwidth to upload inactive data to object storage
          url: task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage
        - title: Move data from the cloud back to the performance tier
          url: task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier
        - title: Manage tiering settings on aggregates
          url: task-managing-tiering.html#managing-tiering-settings-on-aggregates
    - title: Manage object storage
      links:
        - title: Add a new object store for a cluster
          url: task-managing-object-storage.html#adding-a-new-object-store
        - title: Add a second object store to an aggregate for mirroring
          url: task-managing-object-storage.html#attaching-a-second-object-store-to-an-aggregate-for-mirroring
        - title: Swap the primary and mirror object store
          url: task-managing-object-storage.html#swapping-the-primary-and-mirror-object-store
        - title: Remove a mirror object store
          url: task-managing-object-storage.html#removing-a-mirror-object-store-from-an-aggregate
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
        - title: BlueXP tiering blog
          url: https://bluexp.netapp.com/blog/topic/cloud-tiering
        - title: Cloud webinars
          url: https://bluexp.netapp.com/events
    - title: Other resources
      links:
        - title: BlueXP use cases
          url: https://bluexp.netapp.com/cloud-tiering
