settings:
  name: Cloud Tiering
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Cloud Tiering docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Cloud Tiering
          url: /concept-cloud-tiering.html
        - title: Tier on-prem data to the cloud
          entries:
            - title: Tier to Amazon S3
              url: /task-tiering-onprem-aws.html
            - title: Tier to Azure Blob storage
              url: /task-tiering-onprem-azure.html
            - title: Tier to Google Cloud Storage
              url: /task-tiering-onprem-gcp.html
            - title: Tier to StorageGRID
              url: /task-tiering-onprem-storagegrid.html
            - title: Tier to S3 object storage
              url: /task-tiering-onprem-s3-compat.html
        - title: Set up licensing
          url: /task-licensing-cloud-tiering.html
        - title: FAQ
          url: /faq-cloud-tiering.html
    - title: Use Cloud Tiering
      entries:
        - title: Test cloud performance
          url: /task-tiering-test.html
        - title: Manage data tiering
          url: /task-managing-tiering.html
        - title: View tiering overview for all clusters
          url: /task-tiering-onprem-overview.html
        - title: Reference
          entries:
            - title: Supported Amazon S3 storage classes and regions
              url: /reference-aws-support.html
            - title: Supported Azure access tiers and regions
              url: /reference-azure-support.html
            - title: Supported Google Cloud storage classes and regions
              url: /reference-google-support.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
    - title: <tile name>
      links:
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
