---
sidebar: sidebar
permalink: reference-azure-support.html
keywords: microsoft azure, azure, hot, access tier, cold, regions
summary: BlueXP tiering supports two access tiers and most regions.
---

= Supported Azure Blob access tiers and regions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP tiering supports two access tiers and most regions.

== Supported Azure Blob access tiers

When you set up data tiering to Azure, BlueXP tiering automatically uses the _Hot_ access tier for your inactive data. BlueXP tiering can apply a lifecycle rule so the data transitions from the _Hot_ access tier to the _Cool_ access tier after a certain number of days.

If you do not choose the _Cool_ access tier, then the data remains in the _Hot_ access tier and no rules are applied.

When you configure a BlueXP tiering lifecycle rule, you must not configure any lifecycle rules when setting up the container in your Azure account.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview[Learn about Azure Blob access tiers^].

== Supported Azure regions

BlueXP tiering supports tiering to any storage account in any region that can be accessed via the Connector.

//BlueXP tiering supports the following Azure regions.
//
//=== Africa
//
//* South Africa North
//
//=== Asia Pacific
//
//* Australia East
//* Australia Southeast
//* East Asia
//* Japan East
//* Japan West
//* Korea Central
//* Korea South
//* Southeast Asia
//
//=== Europe
//
//* France Central
//* Germany West Central
//* Germany North
//* North Europe
//* UK South
//* UK West
//* West Europe
//
//=== North America
//
//* Canada Central
//* Canada East
//* Central US
//* East US
//* East US 2
//* North Central US
//* South Central US
//* West US
//* West US 2
//* West Central US
//
//=== South America
//
//* Brazil South
