---
sidebar: sidebar
permalink: reference-aws-support.html
keywords: aws, amazon, s3, support, regions, storage classes
summary: BlueXP tiering supports several S3 storage classes and most regions.
---

= Supported S3 storage classes and regions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP tiering supports several S3 storage classes and most regions.

== Supported S3 storage classes

When you set up data tiering to AWS, BlueXP tiering automatically uses the _Standard_ storage class for your inactive data. BlueXP tiering can apply a lifecycle rule so the data transitions from the _Standard_ storage class to another storage class after a certain number of days. You can choose from the following storage classes:

* Standard-Infrequent Access (S3 Standard-IA)
* One Zone-Infrequent Access (S3 One Zone-IA)
* Intelligent-Tiering (S3 Intelligent-Tiering)
* Glacier Instant Retrieval

If you do not choose another storage class, then the data remains in the _Standard_ storage class and no rules are applied.

When you configure a BlueXP tiering lifecycle rule, you must not configure any lifecycle rules when setting up the bucket in your AWS account.

https://aws.amazon.com/s3/storage-classes/[Learn about S3 storage classes^].

== Supported AWS regions

BlueXP tiering supports the following AWS regions.

=== Asia Pacific

* Mumbai
* Seoul
* Singapore
* Sydney
* Tokyo

=== Europe

* Frankfurt
* Ireland
* London
* Paris
* Stockholm

=== North America

* Canada Central
* US East (N. Virginia)
* US East (Ohio)
* US West (N. California)
* US West (Oregon)

=== South America

* São Paulo
