---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering
summary: Learn what's new in Cloud Tiering.
---

= What's new with Cloud Tiering
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in Cloud Tiering.

// tag::whats-new[]
== 3 August 2022

=== Ability to configure additional object stores for other aggregates in your cluster

The Cloud Tiering UI has added a new set of pages for object storage configuration. You can add new object stores, connect multiple object stores to an aggregate for FabricPool Mirroring, swap the primary and mirror object stores, delete object store connections to aggregates, and more. https://docs.netapp.com/us-en/cloud-manager-tiering/task-managing-object-storage.html[Learn more about the new object storage functionality.]

=== Cloud Tiering license support for MetroCluster configurations

Cloud Tiering licenses can now be shared with your clusters that are in MetroCluster configurations. You no longer have to use the deprecated FabricPool licenses for these scenarios. This makes it easier to use the "floating" Cloud Tiering licenses on more of your clusters. https://docs.netapp.com/us-en/cloud-manager-tiering/task-licensing-cloud-tiering.html#apply-cloud-tiering-licenses-to-clusters-in-special-configurations[See how to license and configure these types of clusters.]

== 3 May 2022

=== Cloud Tiering license support for additional cluster configurations

Cloud Tiering licenses can now be shared with your clusters that are in Tiering Mirror configurations (not including MetroCluster configurations) and with clusters that are tiered to IBM Cloud Object Storage. You no longer have to use the deprecated FabricPool licenses for these scenarios. This makes it easier to use the "floating" Cloud Tiering licenses on more of your clusters. https://docs.netapp.com/us-en/cloud-manager-tiering/task-licensing-cloud-tiering.html#apply-cloud-tiering-licenses-to-clusters-in-special-configurations[See how to license and configure these types of clusters.]

== 4 April 2022

=== Amazon S3 Glacier Instant Retrieval storage class is now available

When setting up Cloud Tiering, now you can configure a lifecycle rule so your inactive data transitions from the _Standard_ storage class to _Glacier Instant Retrieval_ after a certain number of days. This will help reduce your AWS infrastructure costs. https://docs.netapp.com/us-en/cloud-manager-tiering/reference-aws-support.html[See the supported S3 storage classes.]

=== Cloud Tiering has been fully qualified on ONTAP Select systems

In addition to tiering data from your AFF and FAS systems, now you can tier inactive data from your ONTAP Select systems to cloud storage.
// end::whats-new[]

== 2 September 2021

=== Cloud Tiering BYOL license replaces FabricPool license

A new *Cloud Tiering* license is now available for tiering configurations that are supported within Cloud Manager using the Cloud Tiering service. It is a floating license that you can use across multiple on-premises ONTAP clusters. The *FabricPool* license that you may have used in the past is retained only for configurations that aren’t supported within Cloud Manager.

https://docs.netapp.com/us-en/cloud-manager-tiering/task-licensing-cloud-tiering.html#use-a-cloud-tiering-byol-license[Learn more about the new Cloud Tiering license].

=== Tier inactive data from on-prem ONTAP clusters to S3-compatible object storage

Now you can tier inactive data to any Object Storage service which uses the Simple Storage Service (S3) protocol. https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-s3-compat.html[See how to tier data to S3-compatible object storage].

== 7 July 2021

=== The Connector can be running on premises when tiering data to Azure Blob storage

You are no longer required to use a Connector installed in an Azure VNet. Your Connector can be running on a host in your premises when tiering data to Azure Blob storage.

== 7 June 2021

=== New tiering classes now available for certain cloud provider storage

In earlier releases you could transition tiered data from the Standard storage class to another storage class after 30 days when using Amazon S3 or Google Cloud object storage. This release adds some new functionality:

* You can choose the number of days when tiered data will move to a more cost-effective tier. This is called data "life cycle management".
* Azure Blob now supports the _Cool_ access tier.
* Google Cloud Storage supports moving tiered data to multiple storage tiers over time. For example, you can move tiered data from the _Standard_ class to the _Nearline_ class after 45 days, and then to the _Coldline_ class after 75 days, and then to the _Archive_ class after 270 days.

=== Now you can proactively move data back to the performance tier from the cloud tier

This functionality is useful if you want to stop using tiering on a volume, or if you decide to keep all user data on the performance tier, but keep Snapshot copies on the cloud tier. This capability is available when using ONTAP 9.8 and greater.

See how to link:task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier[migrate data back to the performance tier].

== 2 May 2021

=== Now you can select all volumes when applying a tiering policy

When selecting the volumes that you want to tier from an ONTAP system, now there's a checkbox in the Tier Volumes page to select *all* volumes to make it easier to apply the same policy to all volumes. link:task-managing-tiering.html#tiering-data-from-additional-volumes[See how to select all volumes in the cluster].

=== Number of "cooling" days can now be set up to 183 days

If you need to change the number of "cooling days" that determine how long data in a volume must remain inactive before it is moved to object storage, now you can specify up to 183 days (up from 63 days) when using ONTAP 9.8 or greater.

== 8 March 2021

=== Lifecycle rules now available when tiering to Google Cloud Storage

When tiering to Google Cloud Storage, you can apply a lifecycle rule so that the tiered data transitions from the Standard storage class to lower-cost Nearline, Coldline, or Archive storage after 30 days.
