---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering
summary: Learn what's new in BlueXP Tiering.
---

= What's new with BlueXP Tiering
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP Tiering.

// tag::whats-new[]
== 3 April 2023

=== Licensing tab has been removed

The Licensing tab has been removed from the BlueXP Tiering interface. All licensing for Pay-as-you-go (PAYGO) subscriptions are accessed from the BlueXP Tiering On-prem Dashboard now. There is also a link from that page to the Digital Wallet so that you can view and manage any BlueXP Tiering bring-your-own-licenses (BYOL).

=== Tiering tabs have been renamed and have updated content

The "Clusters Dashboard" tab has been renamed to "Clusters", and the "On-Prem Overview" tab has been renamed to "On-Prem Dashboard". These pages have added some information that will help you evaluate if you can optimize your storage space with additional tiering configuration.

== 5 March 2023

=== Now you can generate a tiering report for your volumes

You can download a report from the Tier Volumes page so you can review the tiering status of all the volumes on the clusters you are managing. BlueXP Tiering generates a .CSV file that you can review and send to other people in your company as needed. https://docs.netapp.com/us-en/cloud-manager-tiering/task-managing-tiering.html#download-a-tiering-report-for-your-volumes[See how to download the tiering report].

== 6 December 2022

=== Connector outbound internet access endpoint changes

Because of a change in BlueXP Tiering, you need to change the following Connector endpoints for successful BlueXP Tiering operation:

[cols=2*,options="header",cols="50,50",width="80%"]
|===

| Old endpoint
| New endpoint

| \https://cloudmanager.cloud.netapp.com
| \https://api.bluexp.netapp.com
| \https://*.cloudmanager.cloud.netapp.com
| \https://*.api.bluexp.netapp.com

|===

See the full list of endpoints for your https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-set-up-networking-aws.html#outbound-internet-access[AWS^], https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-set-up-networking-google.html#outbound-internet-access[Google Cloud^], or https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-set-up-networking-azure.html#outbound-internet-access[Azure^] cloud environment.
// end::whats-new[]

== 6 November 2022

=== Drag and drop to enable BlueXP Tiering to Azure Blob, Google Cloud Storage, and StorageGRID

If the Azure Blob, Google Cloud Storage, or StorageGRID tiering destination exists as a working environment on the Canvas, you can drag your on-prem ONTAP working environment onto the destination to initiate the Tiering setup wizard.

== 19 September 2022

=== Tiering wizard enables you to configure AWS PrivateLink when tiering to S3 storage

In previous releases it was very time-consuming to provide this secure way of connecting your cluster to an S3 bucket through a VPC endpoint. Now you can follow the prerequisite steps to https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-aws.html#configure-your-system-for-a-private-connection-using-a-vpc-endpoint-interface[configure your system for a private connection using a VPC endpoint interface], and then you can select the PrivateLink during the Tiering setup wizard in the Networking page.

https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-aws.html[Review the requirements and steps to tier inactive data to Amazon S3].

=== Drag and drop to enable BlueXP Tiering to Amazon S3

If the Amazon S3 tiering destination exists as a working environment on the Canvas, you can drag your on-prem ONTAP working environment onto the destination to initiate the Tiering setup wizard.

=== Choose the tiering behavior when removing the mirror object store in a MetroCluster configuration

When removing the mirror object store from a MetroCluster configuration, you’ll be prompted whether you want to remove the primary object store as well. You can choose to keep the primary object store attached to the aggregate, or to remove it.

== 3 August 2022

=== Ability to configure additional object stores for other aggregates in your cluster

The Cloud Tiering UI has added a new set of pages for object storage configuration. You can add new object stores, connect multiple object stores to an aggregate for FabricPool Mirroring, swap the primary and mirror object stores, delete object store connections to aggregates, and more. https://docs.netapp.com/us-en/cloud-manager-tiering/task-managing-object-storage.html[Learn more about the new object storage functionality.]

=== Cloud Tiering license support for MetroCluster configurations

Cloud Tiering licenses can now be shared with your clusters that are in MetroCluster configurations. You no longer have to use the deprecated FabricPool licenses for these scenarios. This makes it easier to use the "floating" Cloud Tiering licenses on more of your clusters. https://docs.netapp.com/us-en/cloud-manager-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations[See how to license and configure these types of clusters.]

== 3 May 2022

=== Cloud Tiering license support for additional cluster configurations

Cloud Tiering licenses can now be shared with your clusters that are in Tiering Mirror configurations (not including MetroCluster configurations) and with clusters that are tiered to IBM Cloud Object Storage. You no longer have to use the deprecated FabricPool licenses for these scenarios. This makes it easier to use the "floating" Cloud Tiering licenses on more of your clusters. https://docs.netapp.com/us-en/cloud-manager-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations[See how to license and configure these types of clusters.]

== 4 April 2022

=== Amazon S3 Glacier Instant Retrieval storage class is now available

When setting up Cloud Tiering, now you can configure a lifecycle rule so your inactive data transitions from the _Standard_ storage class to _Glacier Instant Retrieval_ after a certain number of days. This will help reduce your AWS infrastructure costs. https://docs.netapp.com/us-en/cloud-manager-tiering/reference-aws-support.html[See the supported S3 storage classes.]

=== Cloud Tiering has been fully qualified on ONTAP Select systems

In addition to tiering data from your AFF and FAS systems, now you can tier inactive data from your ONTAP Select systems to cloud storage.
