---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering
summary: Learn what's new in BlueXP tiering.
---

= What's new with BlueXP tiering
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP tiering.

// tag::whats-new[]
== 6 August 2023

=== Use a custom prefix for the bucket name where tiered data is stored

In the past you needed to use the default "fabric-pool" prefix when defining the bucket name, for example, _fabric-pool-bucket1_. Now you can use a custom prefix when naming your bucket. This functionality is available only when tiering data from on-premises ONTAP clusters to Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html[Learn more].

=== Search for a cluster across all BlueXP Connectors

If you are using multiple Connectors to manage all the storage systems in your environment, some clusters on which you want to implement tiering may be in different Connectors. If you are not sure which Connector is managing a certain cluster, you can search across all Connectors using BlueXP tiering. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors[Learn more].

=== More?

more?

== 4 July 2023

=== Now you can adjust the bandwidth used to upload inactive data to object storage

When you activate BlueXP tiering, ONTAP can use an unlimited amount of network bandwidth to transfer the inactive data from volumes in the cluster to object storage. If you notice that tiering traffic is affecting normal user workloads, you can throttle the amount of bandwidth that can be used during the transfer. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage[Learn more].

=== Tiering event for "low tiering" is displayed in the Notification Center

The tiering event "Tier additional data from cluster <name> to object storage to increase your storage efficiency" now appears as a notification when a cluster is tiering less than 20% of its cold data - including clusters that are tiering no data.

This notification is a "Recommendation" to help make your systems more efficient and to save on storage costs. It provides a link to the https://bluexp.netapp.com/cloud-tiering-service-tco[BlueXP tiering total cost of ownership and savings calculator^] to help you calculate your cost savings.

== 3 April 2023

=== Licensing tab has been removed

The Licensing tab has been removed from the BlueXP tiering interface. All licensing for Pay-as-you-go (PAYGO) subscriptions are accessed from the BlueXP tiering On-Premises Dashboard now. There is also a link from that page to the BlueXP digital wallet so that you can view and manage any BlueXP tiering bring-your-own-licenses (BYOL).

=== Tiering tabs have been renamed and have updated content

The "Clusters Dashboard" tab has been renamed to "Clusters", and the "On-Prem Overview" tab has been renamed to "On-Premises Dashboard". These pages have added some information that will help you evaluate if you can optimize your storage space with additional tiering configuration.
// end::whats-new[]

== 5 March 2023

=== Now you can generate a tiering report for your volumes

You can download a report from the Tier Volumes page so you can review the tiering status of all the volumes on the clusters you are managing. BlueXP tiering generates a .CSV file that you can review and send to other people in your company as needed. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#download-a-tiering-report-for-your-volumes[See how to download the tiering report].

== 6 December 2022

=== Connector outbound internet access endpoint changes

Because of a change in BlueXP tiering, you need to change the following Connector endpoints for successful BlueXP tiering operation:

[cols=2*,options="header",cols="50,50",width="80%"]
|===

| Old endpoint
| New endpoint

| \https://cloudmanager.cloud.netapp.com
| \https://api.bluexp.netapp.com
| \https://*.cloudmanager.cloud.netapp.com
| \https://*.api.bluexp.netapp.com

|===

See the full list of endpoints for your https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access[AWS^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access[Google Cloud^], or https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access[Azure^] cloud environment.

== 6 November 2022

=== Drag and drop to enable BlueXP tiering to Azure Blob, Google Cloud Storage, and StorageGRID

If the Azure Blob, Google Cloud Storage, or StorageGRID tiering destination exists as a working environment on the Canvas, you can drag your on-prem ONTAP working environment onto the destination to initiate the Tiering setup wizard.

== 19 September 2022

=== Tiering wizard enables you to configure AWS PrivateLink when tiering to S3 storage

In previous releases it was very time-consuming to provide this secure way of connecting your cluster to an S3 bucket through a VPC endpoint. Now you can follow the prerequisite steps to https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#configure-your-system-for-a-private-connection-using-a-vpc-endpoint-interface[configure your system for a private connection using a VPC endpoint interface], and then you can select the PrivateLink during the Tiering setup wizard in the Networking page.

https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html[Review the requirements and steps to tier inactive data to Amazon S3].

=== Drag and drop to enable BlueXP tiering to Amazon S3

If the Amazon S3 tiering destination exists as a working environment on the Canvas, you can drag your on-prem ONTAP working environment onto the destination to initiate the Tiering setup wizard.

=== Choose the tiering behavior when removing the mirror object store in a MetroCluster configuration

When removing the mirror object store from a MetroCluster configuration, you’ll be prompted whether you want to remove the primary object store as well. You can choose to keep the primary object store attached to the aggregate, or to remove it.

== 3 August 2022

=== Ability to configure additional object stores for other aggregates in your cluster

The Cloud Tiering UI has added a new set of pages for object storage configuration. You can add new object stores, connect multiple object stores to an aggregate for FabricPool Mirroring, swap the primary and mirror object stores, delete object store connections to aggregates, and more. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-object-storage.html[Learn more about the new object storage functionality.]

=== Cloud Tiering license support for MetroCluster configurations

Cloud Tiering licenses can now be shared with your clusters that are in MetroCluster configurations. You no longer have to use the deprecated FabricPool licenses for these scenarios. This makes it easier to use the "floating" Cloud Tiering licenses on more of your clusters. https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations[See how to license and configure these types of clusters.]
