---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering
summary: Learn what's new in Cloud Tiering.
---

= What's new with Cloud Tiering
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in Cloud Tiering.

// tag::whats-new[]
== 3 Apr 2022

=== Support AWS S3 Glacier Instant Retrieval Storage Class

sdfsdsdf

=== Recommendation for Cloud Tiering from Notification panel

sdfsdfsf

== 2 September 2021

=== Cloud Tiering BYOL license replaces FabricPool license.

A new *Cloud Tiering* license is now available for tiering configurations that are supported within Cloud Manager using the Cloud Tiering service. It is a floating license that you can use across multiple on-premises ONTAP clusters. The *FabricPool* license that you may have used in the past is retained only for configurations that aren’t supported within Cloud Manager.

link:task-licensing-cloud-tiering.html#use-a-cloud-tiering-byol-license[Learn more about the new Cloud Tiering license].

=== Tier inactive data from on-prem ONTAP clusters to S3-compatible object storage.

Now you can tier inactive data to any Object Storage service which uses the Simple Storage Service (S3) protocol. link:task-tiering-onprem-s3-compat.html[See how to tier data to S3-compatible object storage].

== 7 July 2021

=== The Connector can be running on premises when tiering data to Azure Blob storage.

You are no longer required to use a Connector installed in an Azure VNet. Your Connector can be running on a host in your premises when tiering data to Azure Blob storage.
// end::whats-new[]

== 7 June 2021

=== New tiering classes now available for certain cloud provider storage.

In earlier releases you could transition tiered data from the Standard storage class to another storage class after 30 days when using Amazon S3 or Google Cloud object storage. This release adds some new functionality:

* You can choose the number of days when tiered data will move to a more cost-effective tier. This is called data "life cycle management".
* Azure Blob now supports the _Cool_ access tier.
* Google Cloud Storage supports moving tiered data to multiple storage tiers over time. For example, you can move tiered data from the _Standard_ class to the _Nearline_ class after 45 days, and then to the _Coldline_ class after 75 days, and then to the _Archive_ class after 270 days.

=== Now you can proactively move data back to the performance tier from the cloud tier.

This functionality is useful if you want to stop using tiering on a volume, or if you decide to keep all user data on the performance tier, but keep Snapshot copies on the cloud tier. This capability is available when using ONTAP 9.8 and greater.

See how to link:task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier[migrate data back to the performance tier].

== 2 May 2021

=== Now you can select all volumes when applying a tiering policy.

When selecting the volumes that you want to tier from an ONTAP system, now there's a checkbox in the Tier Volumes page to select *all* volumes to make it easier to apply the same policy to all volumes. link:task-managing-tiering.html#tiering-data-from-additional-volumes[See how to select all volumes in the cluster].

=== Number of "cooling" days can now be set up to 183 days.

If you need to change the number of "cooling days" that determine how long data in a volume must remain inactive before it is moved to object storage, now you can specify up to 183 days (up from 63 days) when using ONTAP 9.8 or greater.

== 8 Mar 2021

=== Lifecycle rules now available when tiering to Google Cloud Storage.

When tiering to Google Cloud Storage, you can apply a lifecycle rule so that the tiered data transitions from the Standard storage class to lower-cost Nearline, Coldline, or Archive storage after 30 days.
